config/routes.rb
MassHealth::Application.routes.draw do
  resources :town_health_records

  

end

app/models/town_health_record.rb
class TownHealthRecord < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/town_health_records_controller.rb
class TownHealthRecordsController < ApplicationController
  before_action :set_town_health_record, only: [:show, :edit, :update, :destroy]

  # GET /town_health_records
  # GET /town_health_records.json
  def index
    @town_health_records = TownHealthRecord.all
  end

  # GET /town_health_records/1
  # GET /town_health_records/1.json
  def show
  end

  # GET /town_health_records/new
  def new
    @town_health_record = TownHealthRecord.new
  end

  # GET /town_health_records/1/edit
  def edit
  end

  # POST /town_health_records
  # POST /town_health_records.json
  def create
    @town_health_record = TownHealthRecord.new(town_health_record_params)

    respond_to do |format|
      if @town_health_record.save
        format.html { redirect_to @town_health_record, notice: 'Town health record was successfully created.' }
        format.json { render action: 'show', status: :created, location: @town_health_record }
      else
        format.html { render action: 'new' }
        format.json { render json: @town_health_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /town_health_records/1
  # PATCH/PUT /town_health_records/1.json
  def update
    respond_to do |format|
      if @town_health_record.update(town_health_record_params)
        format.html { redirect_to @town_health_record, notice: 'Town health record was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @town_health_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /town_health_records/1
  # DELETE /town_health_records/1.json
  def destroy
    @town_health_record.destroy
    respond_to do |format|
      format.html { redirect_to town_health_records_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_town_health_record
      @town_health_record = TownHealthRecord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def town_health_record_params
      params.require(:town_health_record).permit(:geography, :total_pop_year_2005, :age_0_9_year_2005, :age_65_above_year_2005, :per_capita_income_year_2000, :persons_living_below_200_percent_poverty_year_2000, :percent_all_persons_living_below_200_percent_poverty_level_year_2000, :percent_adequacy_prenatal_care__kotelchuck_, :percent_c_section_deliveries_2005_2008, :number_of_infant_deaths_2005_2008, :infant_mortality_rate__deaths_per_1000_live_births__2005_2008, :percent_low_birthweight_2005_2008, :percent_multiple_births_2005_2008, :percent_publicly_financed_prenatal_care_2005_2008, :percent_teen_births_2005_2008)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/town_health_records_helper.rb
module TownHealthRecordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MassHealth</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/town_health_records/_form.html.erb
<%= form_for(@town_health_record) do |f| %>
  <% if @town_health_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@town_health_record.errors.count, "error") %> prohibited this town_health_record from being saved:</h2>

      <ul>
      <% @town_health_record.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :geography %><br>
    <%= f.text_field :geography %>
  </div>
  <div class="field">
    <%= f.label :total_pop_year_2005 %><br>
    <%= f.number_field :total_pop_year_2005 %>
  </div>
  <div class="field">
    <%= f.label :age_0_9_year_2005 %><br>
    <%= f.number_field :age_0_9_year_2005 %>
  </div>
  <div class="field">
    <%= f.label :age_65_above_year_2005 %><br>
    <%= f.number_field :age_65_above_year_2005 %>
  </div>
  <div class="field">
    <%= f.label :per_capita_income_year_2000 %><br>
    <%= f.text_field :per_capita_income_year_2000 %>
  </div>
  <div class="field">
    <%= f.label :persons_living_below_200_percent_poverty_year_2000 %><br>
    <%= f.number_field :persons_living_below_200_percent_poverty_year_2000 %>
  </div>
  <div class="field">
    <%= f.label :percent_all_persons_living_below_200_percent_poverty_level_year_2000 %><br>
    <%= f.text_field :percent_all_persons_living_below_200_percent_poverty_level_year_2000 %>
  </div>
  <div class="field">
    <%= f.label :percent_adequacy_prenatal_care__kotelchuck_ %><br>
    <%= f.text_field :percent_adequacy_prenatal_care__kotelchuck_ %>
  </div>
  <div class="field">
    <%= f.label :percent_c_section_deliveries_2005_2008 %><br>
    <%= f.text_field :percent_c_section_deliveries_2005_2008 %>
  </div>
  <div class="field">
    <%= f.label :number_of_infant_deaths_2005_2008 %><br>
    <%= f.number_field :number_of_infant_deaths_2005_2008 %>
  </div>
  <div class="field">
    <%= f.label :infant_mortality_rate__deaths_per_1000_live_births__2005_2008 %><br>
    <%= f.number_field :infant_mortality_rate__deaths_per_1000_live_births__2005_2008 %>
  </div>
  <div class="field">
    <%= f.label :percent_low_birthweight_2005_2008 %><br>
    <%= f.text_field :percent_low_birthweight_2005_2008 %>
  </div>
  <div class="field">
    <%= f.label :percent_multiple_births_2005_2008 %><br>
    <%= f.text_field :percent_multiple_births_2005_2008 %>
  </div>
  <div class="field">
    <%= f.label :percent_publicly_financed_prenatal_care_2005_2008 %><br>
    <%= f.text_field :percent_publicly_financed_prenatal_care_2005_2008 %>
  </div>
  <div class="field">
    <%= f.label :percent_teen_births_2005_2008 %><br>
    <%= f.text_field :percent_teen_births_2005_2008 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/town_health_records/edit.html.erb
<h1>Editing town_health_record</h1>

<%= render 'form' %>

<%= link_to 'Show', @town_health_record %> |
<%= link_to 'Back', town_health_records_path %>

app/views/town_health_records/index.html.erb
<h1>Listing town_health_records</h1>

<table>
  <thead>
    <tr>
      <th>Geography</th>
      <th>Total pop year 2005</th>
      <th>Age 0 9 year 2005</th>
      <th>Age 65 above year 2005</th>
      <th>Per capita income year 2000</th>
      <th>Persons living below 200 percent poverty year 2000</th>
      <th>Percent all persons living below 200 percent poverty level year 2000</th>
      <th>Percent adequacy prenatal care  kotelchuck </th>
      <th>Percent c section deliveries 2005 2008</th>
      <th>Number of infant deaths 2005 2008</th>
      <th>Infant mortality rate  deaths per 1000 live births  2005 2008</th>
      <th>Percent low birthweight 2005 2008</th>
      <th>Percent multiple births 2005 2008</th>
      <th>Percent publicly financed prenatal care 2005 2008</th>
      <th>Percent teen births 2005 2008</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @town_health_records.each do |town_health_record| %>
      <tr>
        <td><%= town_health_record.geography %></td>
        <td><%= town_health_record.total_pop_year_2005 %></td>
        <td><%= town_health_record.age_0_9_year_2005 %></td>
        <td><%= town_health_record.age_65_above_year_2005 %></td>
        <td><%= town_health_record.per_capita_income_year_2000 %></td>
        <td><%= town_health_record.persons_living_below_200_percent_poverty_year_2000 %></td>
        <td><%= town_health_record.percent_all_persons_living_below_200_percent_poverty_level_year_2000 %></td>
        <td><%= town_health_record.percent_adequacy_prenatal_care__kotelchuck_ %></td>
        <td><%= town_health_record.percent_c_section_deliveries_2005_2008 %></td>
        <td><%= town_health_record.number_of_infant_deaths_2005_2008 %></td>
        <td><%= town_health_record.infant_mortality_rate__deaths_per_1000_live_births__2005_2008 %></td>
        <td><%= town_health_record.percent_low_birthweight_2005_2008 %></td>
        <td><%= town_health_record.percent_multiple_births_2005_2008 %></td>
        <td><%= town_health_record.percent_publicly_financed_prenatal_care_2005_2008 %></td>
        <td><%= town_health_record.percent_teen_births_2005_2008 %></td>
        <td><%= link_to 'Show', town_health_record %></td>
        <td><%= link_to 'Edit', edit_town_health_record_path(town_health_record) %></td>
        <td><%= link_to 'Destroy', town_health_record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Town health record', new_town_health_record_path %>

app/views/town_health_records/new.html.erb
<h1>New town_health_record</h1>

<%= render 'form' %>

<%= link_to 'Back', town_health_records_path %>

app/views/town_health_records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Geography:</strong>
  <%= @town_health_record.geography %>
</p>

<p>
  <strong>Total pop year 2005:</strong>
  <%= @town_health_record.total_pop_year_2005 %>
</p>

<p>
  <strong>Age 0 9 year 2005:</strong>
  <%= @town_health_record.age_0_9_year_2005 %>
</p>

<p>
  <strong>Age 65 above year 2005:</strong>
  <%= @town_health_record.age_65_above_year_2005 %>
</p>

<p>
  <strong>Per capita income year 2000:</strong>
  <%= @town_health_record.per_capita_income_year_2000 %>
</p>

<p>
  <strong>Persons living below 200 percent poverty year 2000:</strong>
  <%= @town_health_record.persons_living_below_200_percent_poverty_year_2000 %>
</p>

<p>
  <strong>Percent all persons living below 200 percent poverty level year 2000:</strong>
  <%= @town_health_record.percent_all_persons_living_below_200_percent_poverty_level_year_2000 %>
</p>

<p>
  <strong>Percent adequacy prenatal care  kotelchuck :</strong>
  <%= @town_health_record.percent_adequacy_prenatal_care__kotelchuck_ %>
</p>

<p>
  <strong>Percent c section deliveries 2005 2008:</strong>
  <%= @town_health_record.percent_c_section_deliveries_2005_2008 %>
</p>

<p>
  <strong>Number of infant deaths 2005 2008:</strong>
  <%= @town_health_record.number_of_infant_deaths_2005_2008 %>
</p>

<p>
  <strong>Infant mortality rate  deaths per 1000 live births  2005 2008:</strong>
  <%= @town_health_record.infant_mortality_rate__deaths_per_1000_live_births__2005_2008 %>
</p>

<p>
  <strong>Percent low birthweight 2005 2008:</strong>
  <%= @town_health_record.percent_low_birthweight_2005_2008 %>
</p>

<p>
  <strong>Percent multiple births 2005 2008:</strong>
  <%= @town_health_record.percent_multiple_births_2005_2008 %>
</p>

<p>
  <strong>Percent publicly financed prenatal care 2005 2008:</strong>
  <%= @town_health_record.percent_publicly_financed_prenatal_care_2005_2008 %>
</p>

<p>
  <strong>Percent teen births 2005 2008:</strong>
  <%= @town_health_record.percent_teen_births_2005_2008 %>
</p>

<%= link_to 'Edit', edit_town_health_record_path(@town_health_record) %> |
<%= link_to 'Back', town_health_records_path %>